import React, { useEffect } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { you, allEnemies, ascii } from '@/lib/constants/constants';
import { Character, Enemy } from '@/classes/characterClasses';

function constructGrid(): number[] {
  const maxHeight = 21;
  const maxWidth = 5;
  let rowLengths = [];
  const steps = 4;
  for (let i = 0; i <= maxHeight; i++) {
    if (i <= maxHeight - steps) {
      const calcRowLength = i;
      calcRowLength > maxWidth
        ? rowLengths.push(i % 2 === 1 ? maxWidth : maxWidth - 1)
        : rowLengths.push(calcRowLength);
    } else {
      const calcRowLength = maxHeight - i + 1;
      calcRowLength > maxWidth
        ? rowLengths.push(maxWidth)
        : rowLengths.push(calcRowLength);
    }
  }
  return rowLengths;
}

const Home: NextPage = () => {
  const [turns, setTurns] = React.useState(0);
  const [totalTurns, setTotalTurns] = React.useState(0);
  const [depth, setDepth] = React.useState(0);
  const [enemies, setEnemies] = React.useState<Enemy[]>(allEnemies[0]);

  useEffect(() => {
    if (turns > 0) {
      enemies.forEach(enemy => {
        enemy.takeTurn();
      });
    }
  }, [turns]);

  useEffect(() => {
    setEnemies(allEnemies[depth]);
  }, [depth]);

  function descend() {
    console.log('descending to level ' + (depth + 1));
    console.log('total turns: ' + (totalTurns + turns));
    setTotalTurns(totalTurns + turns);
    setTurns(0);
    setDepth(depth + 1);
  }

  const gridRows = constructGrid();
  const baseButton = 'rounded-lg px-2 py-1';
  const blueButton =
    baseButton +
    ' text-white bg-blue-700 border-blue-700 hover:bg-blue-500 hover:border-blue-500';

  function checkTile(i: number, j: number) {
    let char = '';
    if (you.position.x === j && you.position.y === i) {
      char = ascii.spartan;
    } else {
      allEnemies[depth].forEach(enemy => {
        if (enemy.position.x === j && enemy.position.y === i) {
          char = ascii[enemy.aptitude as keyof typeof ascii];
        }
      });
    }
    return char;
  }

  function ConstructGridElement(gridRows: number[]) {
    // const rowClassOld = 'flex flex-row justify-center align-center';
    // const hexClassOld = 'bg-slate-800 border-50 w-10 h-10 rounded-full hover:bg-slate-400 text-center flex flex-col justify-center align-center text-white hover:text-black';
    const rowClass = 'flex flex-row justify-center align-center gap-12';
    const hexClass =
      'bg-slate-800 w-10 h-10 rounded-full hover:bg-slate-400 text-center flex flex-col justify-center align-center text-white hover:text-black my-[-8.5px]';
    return (
      <div className="flex flex-col content-center">
        {[...Array(gridRows.length - 1)].map((x, i) => {
          return (
            <div className={rowClass} key={i}>
              {[...Array(gridRows[i + 1])].map((x, j) => {
                return (
                  <div
                    key={i + ', ' + j}
                    id={'hex-row-' + i + '-col-' + j}
                    className={hexClass}
                  >
                    <p style={{ userSelect: 'none' }}>{checkTile(i, j)}</p>
                  </div>
                );
              })}
            </div>
          );
        })}
      </div>
    );
  }

  return (
    <div className="bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="flex flex-col gap-4">
          {ConstructGridElement(gridRows)}
          <div className="flex justify-evenly mt-[8px]">
            <input type={'button'} className={blueButton} value={'Bash'} />
            <input type={'button'} value={'Hop'} className={blueButton} />
            <input type={'button'} value={'Throw'} className={blueButton} />
          </div>
          <div className="flex justify-center gap-5">
            <input
              type={'button'}
              className={blueButton}
              value={'End Turn'}
              onClick={() => setTurns(turns + 1)}
            />
            <input
              type={'button'}
              value={'Descend'}
              className={blueButton}
              onClick={() => descend()}
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
